# Generated by Django 5.0.6 on 2024-06-07 06:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot_home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pages',
            fields=[
                ('authenticationid_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='bot_home.authenticationid')),
                ('page_name', models.CharField(default='New Page', max_length=255)),
                ('page_token', models.CharField(default='New Token', max_length=255)),
            ],
            bases=('bot_home.authenticationid',),
        ),
    ]
