# Generated by Django 5.0.6 on 2024-06-07 07:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot_home', '0002_pages'),
    ]

    operations = [
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_name', models.CharField(default='New Page', max_length=255)),
                ('page_token', models.CharField(default='New Token', max_length=255)),
                ('user_mail', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pages', to='bot_home.authenticationid')),
            ],
        ),
        migrations.DeleteModel(
            name='Pages',
        ),
    ]
