# Generated by Django 5.0.6 on 2024-06-08 06:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bot_home', '0003_page_delete_pages'),
    ]

    operations = [
        migrations.RenameField(
            model_name='authenticationid',
            old_name='page_id',
            new_name='page_title',
        ),
    ]
